services:
  oracle:
    image: "ghcr.io/rube-de/chatbot-jailbreak:or.1.0"
    build:
      dockerfile: Dockerfile.oracle
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - CONTRACT_ADDRESS=0xF5B786eEb04181AE47C5765d605F778EC0801a6f
    # Removed --ollama-address from entrypoint
    entrypoint: /bin/sh -c 'python main.py --network https://testnet.sapphire.oasis.io $${CONTRACT_ADDRESS}'
    restart: on-failure
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
