services:
  oracle:
    image: "ghcr.io/rube-de/chatbot-jailbreak:or.1.8"
    build:
      context: .
      dockerfile: Dockerfile.oracle
    platform: linux/amd64
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - CONTRACT_ADDRESS=0x859f08C3D9F3030771E5f249e5F599e8DEa1FC75
    # Removed --ollama-address from entrypoint
    entrypoint: /bin/sh -c 'python main.py --network https://testnet.sapphire.oasis.io $${CONTRACT_ADDRESS}'
    restart: on-failure
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
