services:
  ollama:
    image: "docker.io/ollama/ollama"
    ports:
      - "11434:11434"
    volumes:
      - /storage/ollama:/root/.ollama
    entrypoint: ["/usr/bin/bash", "-c", "/bin/ollama serve & sleep 5; ollama pull deepseek-r1:1.5b; wait"]

  oracle:
    environment:
      CONTRACT_ADDRESS: 0xBB333702465ea39eF0367490550C30B2515eE2CD
    image: "ghcr.io/rube-de/chatbot-jailbreak:0.1.27"
    entrypoint: /bin/sh -c 'python main.py --network https://testnet.sapphire.oasis.io --ollama-address http://ollama:11434 0xBB333702465ea39eF0367490550C30B2515eE2CD'
    restart: on-failure
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
