FROM ghcr.io/foundry-rs/foundry:stable AS contracts-build
WORKDIR /contracts
COPY ./contracts /contracts
RUN forge build

FROM python:alpine3.17 AS oracle
#ENV CONTRACT_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3 # Must be defined in compose.yaml
WORKDIR /oracle
COPY ./oracle /oracle
COPY --from=contracts-build /contracts /contracts
RUN apk update && \
    apk add --no-cache python3-dev gcc libc-dev && \
    pip install --no-cache-dir -r requirements.txt
ENTRYPOINT ["python", "main.py", "${CONTRACT_ADDRESS}"]
